// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';

export function GetGithubRepositories(arg1:string):Promise<Array<github.Repository>>;
